### ISSUE TITLE
Consider hosting Fabrice Prigent's adult blocklist instead of Chad Mayfield's

### ISSUE THREAD

**Issue by ghost** [WaLLy3K/wally3k.github.io#100] opened 2020-05-11 21:31 UTC
As it stands, Chad Mayfield's "all" blocklist [is a clone of](https://github.com/chadmayfield/my-pihole-blocklists/blob/cb98587ab92f368bc7152c5cee6e56b667da30ea/create_blocklist_porn.pl#L32-L33) Fabrice Prigent's blocklist, and the "top 1M" blocklist only contains domains that appear on Alexa's top 1 million sites list.

The issue is, Chad Mayfield's repo hasn't been updated in over 4 months (perhaps because Alexa stopped publishing the top 1M list), but Fabrice Prigent's adult list has been updated frequently. Since Fabrice Prigent's blocklists are gzipped, would you consider mirroring the adult list on v.firebog.net?

https://dsi.ut-capitole.fr/blacklists/index_en.php

@chadmayfield

**Comment by ACMEd** [comment] 2020-05-11 22:07
Also consider hosting Fabrice Prigent's cryptojacking blocklist.

**Comment by WaLLy3K** [comment] 2020-05-12 01:15
I already have tools in place to support Fabrice’s site, so yeah I can definitely check those two out!

**Comment by WaLLy3K** [comment] 2020-05-19 01:01
This isn't something I can do immediately, as the VPS I'm currently hosting has a PHP (ugh) configuration that's causing it to run out of memory when trying to extract this list, and I don't have root/sudo access to this box in order to fix it.

I'll look into resolving this, but it's going to be a low-ish priority over the next month or so.

**Comment by WaLLy3K** [comment] 2020-05-19 01:03
Fabrice's Cryptojacking Blocklist: https://v.firebog.net/hosts/Prigent-Crypto.txt

**Comment by WaLLy3K** [comment] 2020-05-20 23:53
I'm slowly pottering away on porting my parser from PHP5 to bash (and other things relating to the VPS migration), so I'll keep this ticket open until the issue is resolved.

**Comment by Zelo72** [comment] 2021-08-06 20:47
Yes, the list is huge, ported it using shell script. The list is updated daily. Raw link: https://raw.githubusercontent.com/Zelo72/rpi/master/pihole/blocklists/prigentadult.txt

**Comment by StuartMorrisAU** [comment] 2021-10-10 00:04
FYI - @chadmayfield’s [repo](https://github.com/chadmayfield/my-pihole-blocklists) has been archived.

**Comment by Grocel** [comment] 2021-10-10 13:04
Apparently Zelo72's list got removed.

**Comment by Zelo72** [comment] 2021-10-10 14:05
@Grocel 

You can find them in the @cbuijs repository, there are all ut1 lists available in domain format:
https://github.com/cbuijs/ut1/tree/master/adult

**Closed** 2021-12-04 23:56 UTC
Labels: in progress

**Comment by WaLLy3K** [comment] 2021-12-04 23:58
Doesn't look like that repo contains the extracted lists anymore, which is a bit of a shame.

I've been able to parse Prigent's Adult blacklist, but it's a 15Mb archive that blows out to a **whopping 90Mb** with 3.4 million lines. I just hope Cloudflare doesn't get peeved off when this file starts seeing a lot of automated hits - I already get 400K unique hits a month as is. 😅

**Comment by cbuijs** [comment] 2021-12-13 03:48
The unpacked lists should be back soon. My node taking care of it crashed and will be fully back up soon.
