### ISSUE TITLE
github.io in EasyPrivacy list

### ISSUE THREAD

**Issue by mazesy** [WaLLy3K/wally3k.github.io#14] opened 2018-02-13 23:02 UTC
Hi,

I daily download several blocklists available at your https://wally3k.github.io/ page.

Using the https://v.firebog.net/hosts/Easyprivacy.txt list is problematic because it includes as such `github.io` which, at least when processed by DNSCrypt-proxy (blocklist) blocks access to all github.io sites (it's understood as *.github.io) which means that https://wally3k.github.io/ itself is blocked!

Other lists mention specific github.io pages, but not plain github.io ...

Thanks for your work, @WaLLy3K ,  much appreciated.

**Comment by WaLLy3K** [comment] 2018-02-27 07:02
Looking at [EasyPrivacy's source list](https://easylist.to/easylist/easyprivacy.txt), the relevant lines are:

    ||github.io/*.wasm$third-party
This should be ignored by my parser, as it isn't a standalone domain

    ||github.io^$third-party,websocket
This is what's being processed as a valid domain.

[This is the official documentation on the WebSocket filter](https://adblockplus.org/development-builds/new-filter-type-option-for-websockets), which for all intents and purposes, should be blocked at the DNS level. It's really unfortunate that `github.io` has been caught up in this, but as far as I'm aware, I'm parsing the list correctly.

It's unfortunate that `DNSCrypt-proxy` is blocking access to all subdomains though - that's definitely not how a blocklist parser should be interpreting HOSTS based domains. :slightly_frowning_face: 

I'm interested to hear your thoughts on the matter before I action this issue further!

**Comment by mazesy** [comment] 2018-02-27 10:14
Thanks for acknowledging, @WaLLy3K --Today, and perhaps since my post above, the issue is resolved: no plain `github.io` in the list. Thanks.

**Comment by WaLLy3K** [comment] 2018-02-27 10:30
> Thanks for acknowledging, @WaLLy3K 

I apologise for the delay in initial response! I've had trouble keeping on top of my GitHub mentions, but I've sorted that out now.

> Today, and perhaps since my post above, the issue is resolved: no plain github.io in the list. 

From what I can see, `github.io` is still there though? Line 2326 in [Easyprivacy.txt](https://v.firebog.net/hosts/Easyprivacy.txt)

> Thanks, as well for your lists, most valuable.

Cheers :beers: :slightly_smiling_face:

**Comment by mazesy** [comment] 2018-02-27 10:49
From what I can see, github.io is still there though? Line 2326 in Easyprivacy.txt

My fault. I had forgotten that I had removed the https://v.firebog.net/hosts/Easyprivacy.txt list from my daily lists' updates because of the issue (I still have Esayprivacy filters but only at the browser level with that list handled by uBlock Origin)

At this time I download your following lists with a few others:

IMPORT-DOM-05.txt = https://v.firebog.net/hosts/Prigent-Ads.txt
IMPORT-DOM-06.txt = https://v.firebog.net/hosts/Prigent-Malware.txt
IMPORT-DOM-07.txt = https://v.firebog.net/hosts/AdguardDNS.txt
IMPORT-DOM-08.txt = https://v.firebog.net/hosts/Easylist.txt
IMPORT-DOM-09.txt = https://v.firebog.net/hosts/Shalla-mal.txt

No problem with those.
We handle so many settings nowadays that we sometimes forget what we changed, hoping we where aware of why we changed it (I try to be).

I guess I have no reason to re-include https://v.firebog.net/hosts/Easyprivacy.txt at this time given github.io is still listed.

Thanks for the follow-up, @WaLLy3K

**Comment by WaLLy3K** [comment] 2018-02-27 23:17
No worries at all! Given that the inclusion of `github.io` is expected behavior due to the source list (and no reason to not include websocket blocks as of yet), I'll go ahead and close this ticket.

If there's anything else I can do to help, please be sure to let me know :slightly_smiling_face:

**Closed by WaLLy3K** 2018-02-27 23:17 UTC
